# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30, unique=True)),
                ('LastName', models.CharField(max_length=30, unique=True)),
                ('Email', models.EmailField(max_length=40, unique=True)),
            ],
        ),
    ]
